DELETE http://localhost:3001/api/persons/5ffc47ece99d33120071c761

###
GET http://localhost:3001/api/persons/

### 
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Anna",
    "number": "50"
}

###
PUT http://localhost:3001/api/persons/5ffc0dfd8e81fe103bdbf01a
Content-Type: application/json

{
    "name": "John Travolta",
    "number": "505-505-5099"
}